services:
  removercontatos: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:8090"
      - "5011:8091"
    networks:
      - monitoring
networks:
  monitoring:
    external: true 
