services:
  consumerremovercontatos: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5096:8096"
      - "5097:8097"
    networks:
      - monitoring
networks:
  monitoring:
    external: true 
